import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import SearchFilter from '@/components/SearchFilter';

export const metadata: Metadata = {
  title: 'Country App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <SearchFilter />
        {children}
      </body>
    </html>
  );
}
